# Generated by Django 4.2.3 on 2023-07-27 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyYotubeVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoName', models.CharField(max_length=1000)),
                ('thumbnail', models.URLField(default='https://shit.management/content/images/size/w2000/2019/07/team_work.jpg')),
                ('description', models.TextField()),
                ('url', models.CharField(default='default', max_length=5000, null=True)),
            ],
            options={
                'verbose_name': 'MyYotubeVideo',
                'verbose_name_plural': 'MyYotubeVideos',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
