# Generated by Django 4.2.3 on 2023-07-29 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubeDB', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriberStories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storyTitle', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=1000)),
                ('story', models.TextField()),
            ],
            options={
                'verbose_name': 'SubscriberStorie',
                'verbose_name_plural': 'SubscriberStories',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
