# Generated by Django 4.2.3 on 2023-07-29 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubeDB', '0004_youtubeevents_eventimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubeevents',
            name='eventImage',
            field=models.URLField(blank=True),
        ),
    ]
