# Generated by Django 4.2.3 on 2023-07-31 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubeDB', '0005_alter_youtubeevents_eventimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MileStones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestoneName', models.CharField(max_length=1000)),
                ('mileStoneDate', models.DateField()),
            ],
            options={
                'verbose_name': 'MileStone',
                'verbose_name_plural': 'MileStones',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
