# Generated by Django 4.2.3 on 2023-07-18 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_projects_options_alter_projects_projectname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='video',
            field=models.URLField(null=True),
        ),
    ]
