# Generated by Django 4.2.3 on 2023-07-18 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_projects_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='projectImage',
            field=models.URLField(default='https://shit.management/content/images/size/w2000/2019/07/team_work.jpg'),
        ),
    ]
