# Generated by Django 4.2.3 on 2023-07-18 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_projects_url_alter_projects_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='url',
            field=models.CharField(default='default', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='video',
            field=models.CharField(default='default', max_length=5000, null=True),
        ),
    ]
